### ISSUE TITLE
Docker file missing vsdbg location?

### ISSUE THREAD

**Issue by alanmbarr** [okteto/aspnetcore-getting-started#7]
I was not sure if this was intentional. After -l I was expecting the vsdbg path in launch.json. This doesn't impact anything just confused me when I was attempting to debug another issue without interacting with kubernetes.

https://github.com/okteto/aspnetcore-getting-started/blob/9e62221e47227883f48b0b85b2274a9fd5abebb7/Dockerfile#L5

**Comment by rberrelleza** [comment]
This is now coming from the devenv image.
